"""Recursive cognitive metabolism tying invention mechanisms into one closed loop.

The purpose of this module is integration, not another isolated capability demo. A
validated invented representation becomes knowledge; that knowledge is evidence for a
self-authored goal; the goal requires a constructed action; the constructed action is
validated into a reusable tool; resulting prediction errors can trigger another round of
representation invention. Discoveries therefore change the inputs to future cognition.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from ix_sally.cognition.lifelong import KnowledgeItem, LifelongKnowledgeStore
from ix_sally.cognition.open_choice import ActionPrimitive, OpenChoiceSynthesizer
from ix_sally.cognition.open_goals import GeneratedGoal, IntrinsicDrives, OpenGoalGenesis
from ix_sally.cognition.representation import (
    InventedRepresentation,
    RepresentationInventor,
    RepresentationObservation,
    SemanticPrimitive,
)
from ix_sally.cognition.tool_forge import ForgedTool, ToolForge, ToolValidationCase
from ix_sally.cognition.unknowns import PredictionResidual, UnknownUnknownDetector, UnknownUnknownSignal
from ix_sally.digest import DigestRecord, JsonObject
from ix_sally.foundation import FoundationError


@dataclass(frozen=True, slots=True)
class RecursiveBootstrapReport:
    """Evidence receipt for one closed cognitive bootstrapping cycle."""

    first_representation: InventedRepresentation
    first_semantic_primitive: SemanticPrimitive
    generated_goal: GeneratedGoal
    constructed_action_id: str
    forged_tool: ForgedTool
    unknown_unknown: UnknownUnknownSignal
    second_representation: InventedRepresentation | None
    knowledge_store: LifelongKnowledgeStore

    @property
    def recursive_growth_demonstrated(self) -> bool:
        return (
            self.first_representation.validation_accuracy == 1.0
            and self.forged_tool.validation_accuracy == 1.0
            and self.generated_goal.goal.evidence_digests
            and (
                not self.unknown_unknown.detected
                or self.second_representation is not None
            )
        )

    def to_payload(self) -> JsonObject:
        second = self.second_representation.to_payload() if self.second_representation else None
        return {
            "first_representation": self.first_representation.to_payload(),
            "first_semantic_primitive": self.first_semantic_primitive.to_payload(),
            "generated_goal": self.generated_goal.to_payload(),
            "constructed_action_id": self.constructed_action_id,
            "forged_tool": self.forged_tool.to_payload(),
            "unknown_unknown": {
                "detected": self.unknown_unknown.detected,
                "high_confidence_error_rate": self.unknown_unknown.high_confidence_error_rate,
                "dominant_context": list(self.unknown_unknown.dominant_context)
                if self.unknown_unknown.dominant_context is not None
                else None,
                "dominant_context_errors": self.unknown_unknown.dominant_context_errors,
                "reason": self.unknown_unknown.reason,
            },
            "second_representation": second,
            "knowledge_store": self.knowledge_store.to_payload(),
            "recursive_growth_demonstrated": self.recursive_growth_demonstrated,
        }


class RecursiveCognitionEngine:
    """Run a bounded discover → goal → act → tool → rediscover cycle."""

    def bootstrap(
        self,
        *,
        representation_training: Iterable[RepresentationObservation],
        representation_holdout: Iterable[RepresentationObservation],
        initial_state: int,
        primitives: Iterable[ActionPrimitive],
        known_states: Iterable[int],
        tool_validation_cases: Iterable[ToolValidationCase],
        residuals: Iterable[PredictionResidual] = (),
        second_representation_training: Iterable[RepresentationObservation] = (),
        second_representation_holdout: Iterable[RepresentationObservation] = (),
        max_goal_depth: int = 4,
    ) -> RecursiveBootstrapReport:
        base_primitives = tuple(primitives)
        if not base_primitives:
            raise FoundationError("recursive cognition requires action primitives")

        inventor = RepresentationInventor()
        first = inventor.invent_binary(observations=representation_training)
        first = inventor.validate(first, observations=representation_holdout)
        semantic = inventor.promote(first)

        # The invented semantic becomes evidence for a new internally-authored goal. The target
        # itself is still generated by OpenGoalGenesis; the semantic is not allowed to hard-code it.
        goal = OpenGoalGenesis().generate(
            initial_state=initial_state,
            primitives=base_primitives,
            known_states=known_states,
            drives=IntrinsicDrives(),
            max_depth=max_goal_depth,
        )
        evidence = (*goal.goal.evidence_digests, first.digest())
        from ix_sally.cognition.goals import GoalSpec

        evidence_bound_goal = GoalSpec.create(
            goal_id=goal.goal.goal_id.value,
            description=(
                goal.goal.description
                + " The objective was authored only after a validated machine-invented representation entered cognition."
            ),
            desired_state=goal.goal.desired_state,
            priority=goal.goal.priority,
            utility=goal.goal.utility,
            risk_limit=goal.goal.risk_limit,
            status=goal.goal.status,
            dependency_ids=(item.value for item in goal.goal.dependency_ids),
            authority_required=goal.goal.authority_required,
            evidence_digests=evidence,
        )
        goal = GeneratedGoal(
            goal=evidence_bound_goal,
            initial_state=goal.initial_state,
            target_state=goal.target_state,
            generating_program=goal.generating_program,
            intrinsic_score=goal.intrinsic_score,
            novelty=goal.novelty,
            information_gain=goal.information_gain,
            competence_expansion=goal.competence_expansion,
            simplicity=goal.simplicity,
            reversibility=goal.reversibility,
            risk=goal.risk,
            origin=goal.origin,
        )

        choice = OpenChoiceSynthesizer().synthesize(
            initial_state=initial_state,
            goal_test=lambda state: state == goal.target_state,
            primitives=base_primitives,
            max_depth=max_goal_depth + 2,
        )
        tool = ToolForge().forge(
            action=choice.selected,
            primitives=base_primitives,
            validation_cases=tool_validation_cases,
        )
        if tool.validation_accuracy != 1.0:
            raise FoundationError("constructed action failed independent tool validation")

        store = LifelongKnowledgeStore()
        store = store.integrate(
            KnowledgeItem(
                concept_id=semantic.primitive_id,
                content_digest=first.digest(),
                confidence=1.0,
                utility=0.8,
            )
        )
        store = store.integrate(
            KnowledgeItem(
                concept_id=tool.tool_id,
                content_digest=DigestRecord.from_payload(tool.to_payload()),
                confidence=tool.validation_accuracy,
                utility=0.9,
            )
        )

        residual_tuple = tuple(residuals)
        signal = (
            UnknownUnknownDetector().detect(residual_tuple)
            if residual_tuple
            else UnknownUnknownSignal(False, 0.0, None, 0, "No post-action residuals were supplied.")
        )
        second: InventedRepresentation | None = None
        if signal.detected:
            training2 = tuple(second_representation_training)
            holdout2 = tuple(second_representation_holdout)
            if not training2 or not holdout2:
                raise FoundationError(
                    "unknown-unknown signal requires evidence for a second representation attempt"
                )
            second = inventor.invent_binary(observations=training2)
            second = inventor.validate(second, observations=holdout2)
            second_semantic = inventor.promote(second)
            store = store.integrate(
                KnowledgeItem(
                    concept_id=second_semantic.primitive_id,
                    content_digest=second.digest(),
                    confidence=1.0,
                    utility=0.85,
                )
            )

        return RecursiveBootstrapReport(
            first_representation=first,
            first_semantic_primitive=semantic,
            generated_goal=goal,
            constructed_action_id=choice.selected.action_id,
            forged_tool=tool,
            unknown_unknown=signal,
            second_representation=second,
            knowledge_store=store,
        )
